spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8072/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
    routes[0]:
      id: "order-service"
      uri: "lb://order-service"
      predicates[0]: "Path=/api/order/**"
      predicates[1]: Header=Authorization, Bearer (.*)  # Match all headers
      filters[0:
        - RemoveRequestHeader=Cookie
  data:
    redis:
      connect-timeout: 3s
      host: localhost
      port: 6379
      timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "KuoShengclement ECommerce Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      ecommerce:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

